export const COMPETITOR_ORDER = [
  "pabau",
  "treatwell",
  "fresha",
  "phorest",
  "aesthetic-record",
  "glowday",
  "mindbody",
  "cliniko",
  "semble",
  "repeatmd",
  "zenoti",
  "vagaro",
  "boulevard",
  "jane-app",
  "square-appointments",
  "timely",
  "acuity-scheduling",
  "calendly",
  "google-forms",
  "paper-consent-forms",
  "spreadsheets",
] as const

export type CompetitorSlug = (typeof COMPETITOR_ORDER)[number]

export const COMPETITOR_LABEL: Record<string, string> = {
  pabau: "Pabau",
  treatwell: "Treatwell",
  fresha: "Fresha",
  phorest: "Phorest",
  "aesthetic-record": "Aesthetic Record",
  glowday: "Glowday",
  mindbody: "Mindbody",
  cliniko: "Cliniko",
  semble: "Semble",
  repeatmd: "RepeatMD",
  zenoti: "Zenoti",
  vagaro: "Vagaro",
  boulevard: "Boulevard",
  "jane-app": "Jane App",
  "square-appointments": "Square Appointments",
  timely: "Timely",
  "acuity-scheduling": "Acuity Scheduling",
  calendly: "Calendly",
  "google-forms": "Google Forms",
  "paper-consent-forms": "Paper Consent Forms",
  spreadsheets: "Spreadsheets",
}
