import { z } from "zod"

export const clinicSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, 'Slug must be kebab-case (lowercase letters, numbers, hyphens only)'),
  image: z.string().url('Image must be a valid URL'),
  url: z.string().url('URL must be a valid URL'),
  rating: z.number().min(0).max(5, 'Rating must be between 0 and 5'),
  reviewCount: z.number().int().min(0, 'Review count must be a non-negative integer'),
  category: z.string().min(1, 'Category is required'),
  gmapsAddress: z.string().min(1, 'Address is required'),
  gmapsPhone: z.string().optional(),
  gmapsReviews: z.array(z.object({
    reviewer_name: z.string().min(1),
    rating: z.string().min(1),
    date: z.string().min(1),
    review_text: z.string().optional(),
    owner_response: z.string().nullable()
  })).optional(),
  reviewAnalysis: z.any().optional(),
  weighted_analysis: z.any().optional(),
  City: z.string().min(1, 'City is required'),
  facebook: z.string().optional(),
  twitter: z.string().optional(),
  Linkedin: z.string().optional(),
  instagram: z.string().optional(),
  youtube: z.string().optional(),
  website: z.string().url().optional(),
  email: z.string().email().optional().or(z.literal('')),
  isSaveFace: z.boolean(),
  isDoctor: z.boolean(),
  isJCCP: z.tuple([z.boolean(), z.string()]).nullable().optional(),
  isCQC: z.tuple([z.boolean(), z.string()]).nullable().optional(),
  isHIW: z.tuple([z.boolean(), z.string()]).nullable().optional(),
  isHIS: z.tuple([z.boolean(), z.string()]).nullable().optional(),
  isRQIA: z.tuple([z.boolean(), z.string()]).nullable().optional(),
  about_section: z.string().optional(),
  accreditations: z.string().optional(),
  awards: z.string().optional(),
  affiliations: z.string().optional(),
  hours: z.string().optional(),
  Practitioners: z.string().optional(),
  Insurace: z.string().optional(),
  Payments: z.string().optional(),
  Fees: z.string().optional(),
  x_twitter: z.string().optional(),
  Treatments: z.array(z.string()).optional()
})

export type ClinicInput = z.infer<typeof clinicSchema>

// Admin edit schema — uses Prisma field names directly, all fields optional
export const clinicEditSchema = z.object({
  name: z.string().optional().nullable(),
  image: z.string().optional().nullable(),
  gmapsUrl: z.string().optional().nullable(),
  gmapsAddress: z.string().optional().nullable(),
  gmapsPhone: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  rating: z.coerce.number().min(0).max(5).optional().nullable(),
  reviewCount: z.coerce.number().int().min(0).optional().nullable(),
  aboutSection: z.string().optional().nullable(),
  accreditations: z.string().optional().nullable(),
  awards: z.string().optional().nullable(),
  affiliations: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  facebook: z.string().optional().nullable(),
  twitter: z.string().optional().nullable(),
  xTwitter: z.string().optional().nullable(),
  instagram: z.string().optional().nullable(),
  youtube: z.string().optional().nullable(),
  linkedin: z.string().optional().nullable(),
  isSaveFace: z.boolean().optional(),
  isDoctor: z.boolean().optional(),
  isJccp: z.boolean().optional().nullable(),
  jccpUrl: z.string().optional().nullable(),
  isCqc: z.boolean().optional().nullable(),
  cqcUrl: z.string().optional().nullable(),
  isHiw: z.boolean().optional().nullable(),
  hiwUrl: z.string().optional().nullable(),
  isHis: z.boolean().optional().nullable(),
  hisUrl: z.string().optional().nullable(),
  isRqia: z.boolean().optional().nullable(),
  rqiaUrl: z.string().optional().nullable(),
})

export type ClinicEditInput = z.infer<typeof clinicEditSchema>
